version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: es01
    environment:
      - node.name=es01
      - node.roles=master,data_hot,data_content
      - discovery.seed_hosts=es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../esdata/es01:/usr/share/elasticsearch/data
      - ./config/${ES_CONFIG}:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: es02
    environment:
      - node.name=es02
      - node.roles=master,data_hot,data_content
      - discovery.seed_hosts=es01,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../esdata/es02:/usr/share/elasticsearch/data
      - ./config/${ES_CONFIG}:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: es03
    environment:
      - node.name=es03
      - node.roles=master,data_hot,data_content
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../esdata/es03:/usr/share/elasticsearch/data
      - ./config/${ES_CONFIG}:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
  es04:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: es04
    environment:
      - node.name=es04
      - node.roles=data_warm,data_content
      - discovery.seed_hosts=es01,es02,es3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../esdata/es04:/usr/share/elasticsearch/data
      - ./config/${ES_CONFIG}:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    container_name: kibana
    restart: on-failure
    volumes:
      - ./config/kibana.yaml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic
    ports:
      - 5601:5601

networks:
  elastic:
    driver: bridge