---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
#
cluster.name: "docker-cluster"
cluster.initial_master_nodes: [ es01, es02, es03 ]
network.host: 0.0.0.0


# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
#discovery.zen.minimum_master_nodes: 3
discovery.type: multi-node

xpack.security.enabled: false
logger.org.elasticsearch.discovery: DEBUG

## Use single node discovery in order to disable production mode and avoid bootstrap checks
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
#discovery.type: single-node

# Path to directory where to store index data allocated for this node.
#

## lifecycle 
indices.lifecycle.poll_interval: 1m
# indices.memory.index_buffer_size: 10%
# indices.memory.min_index_buffer_size: 48mb